apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: testkamiyamak
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kamiyamak-guestbook.istyle.local
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 3000
