apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
  namespace: default
  labels: 
    app: weblog
    type: storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: "./data/storage"
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany

